const SET_INSTITUTION = 'SET_INSTITUTION';
const CLEAR_INSTITUTION = 'CLEAR_INSTITUTION';
const SET_INSTITUTION_GROUPS = 'SET_INSTITUTION_GROUPS';
const ADD_INSTITUTION_USER = 'ADD_INSTITUTION_USER';
const REMOVE_INSTITUTION_USER = 'REMOVE_INSTITUTION_USER';

export default Object.freeze({
  SET_INSTITUTION,
  CLEAR_INSTITUTION,
  SET_INSTITUTION_GROUPS,
  ADD_INSTITUTION_USER,
  REMOVE_INSTITUTION_USER
});
