const APP_BASE_URL = 'APP_BASE_URL';
const APP_DEBUG = 'APP_DEBUG';
const APP_ENV = 'APP_ENV';
const MAIN_BASE_URL = 'MAIN_BASE_URL';
const MERCURE_PUBLISH_URL = 'MERCURE_PUBLISH_URL';

export default Object.freeze({
  APP_BASE_URL,
  APP_DEBUG,
  APP_ENV,
  MAIN_BASE_URL,
  MERCURE_PUBLISH_URL
});
